# -*- coding: utf-8 -*-
"""lista_de_exercicio_03_gabriel_moises_alves.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4bPqhp7n-LofY7o2u_A8bMgAumgwCU8

# LISTA DE EXERCÍCIO – 03: Gabriel Moises Alves
"""

import numpy as np

class Listasequencial:

    def __init__(self, capacidade):
        self.capacidade = capacidade
        self.ultima_posicao = -1
        self.valores = np.empty(self.capacidade, dtype=int)

    def imprime(self):
        if self.ultima_posicao == -1:
            print('O vetor está vazio')
        else:
            for i in range(self.ultima_posicao + 1):
                print(i,' - ',self.valores[i])

    def insere(self, valor):
        if self.ultima_posicao == self.capacidade - 1:
            print('Capacidade máxima atingida...')
        else:
            self.ultima_posicao += 1
            self.valores[self.ultima_posicao] = valor

    def pesquisar(self, valor):
        for i in range(self.ultima_posicao + 1):
            if (valor==self.valores[i]):
                return i
        return -1

    def excluir(self, valor):
        posicao = self.pesquisar(valor)
        if posicao == -1:
            return -1
        else:
            for i in range(posicao, self.ultima_posicao):
                self.valores[i] = self.valores[i + 1]
        self.ultima_posicao -= 1

# 1.
lista_matriculas = Listasequencial(5)

lista_matriculas.insere(101)
lista_matriculas.insere(102)
lista_matriculas.insere(103)
lista_matriculas.insere(104)

lista_matriculas.imprime()

# 2.
produtos_codigos = Listasequencial(5)

produtos_codigos.insere(45)
produtos_codigos.insere(33)
produtos_codigos.insere(27)
produtos_codigos.insere(89)
produtos_codigos.insere(56)

produtos_codigos.insere(72)
# Capacidade máxima atingida...

# 3.
clientes_codigos = Listasequencial(5)

clientes_codigos.insere(11)
clientes_codigos.insere(22)
clientes_codigos.insere(33)
clientes_codigos.insere(44)
clientes_codigos.insere(55)

print(f'Posição na lista do cliente código 33: {clientes_codigos.pesquisar(33)}')

# 4.
clientes = Listasequencial(5)

clientes.insere(10)
clientes.insere(20)
clientes.insere(30)
clientes.insere(40)
clientes.insere(50)

clientes.excluir(30)

clientes.imprime()

# 5.
pacientes = Listasequencial(5)

pacientes.insere(5)
pacientes.insere(6)
pacientes.insere(7)
pacientes.insere(8)
pacientes.insere(9)

pacientes.excluir(7)

pacientes.imprime()

# 6.
reservas = Listasequencial(6)

reservas.insere(101)
reservas.insere(103)
reservas.insere(107)
reservas.insere(110)
reservas.insere(115)

reservaConsulta = int(input("Digite o número da reserva: "))

if (reservas.pesquisar(reservaConsulta) == -1):
  print(f'\nA reserva {reservaConsulta} está disponível.')
else:
  print(f'\nA reserva {reservaConsulta} já foi cadastrada.')

# 7.
pedidos = Listasequencial(5)

pedidos.insere(2001)
pedidos.insere(2002)
pedidos.insere(2003)
pedidos.insere(2004)
pedidos.insere(2005)

pedidos.excluir(2002)

pedidos.imprime()

# 8.
carros_placas = Listasequencial(4)

carros_placas.insere(1234)
carros_placas.insere(5678)
carros_placas.insere(9101)
carros_placas.insere(1213)

placaConsulta = 5678

if (carros_placas.pesquisar(placaConsulta) == -1):
  print(f'\nA placa {placaConsulta} não está estacionada.')
else:
  print(f'\nA placa {placaConsulta} está estacionada.')

carros_placas.insere(1415)
# Capacidade máxima atingida...

# 9.
notas = Listasequencial(5)

notas.insere(70)
notas.insere(85)
notas.insere(90)
notas.insere(75)
notas.insere(60)

notaPesquisa = notas.pesquisar(75)

if (notaPesquisa == -1):
  print('A nota 75 não foi encontrada.')
else:
  print(f'A nota 75 foi encontrada na posição: {notaPesquisa}')

# 10.
valores = Listasequencial(6)

for i in range(1, 7):
  valores.insere(i)

valores.excluir(3)
valores.imprime()
print()
valores.excluir(5)
valores.imprime()