# -*- coding: utf-8 -*-
"""lista_de_exercicio_02_gabriel_moises_alves.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8gqk0pjT7e9wHg2i3syaOpM5k7AnL3I

# LISTA DE EXERCÍCIO – 02: Gabriel Moises Alves
"""

# 1.
import math

class Circulo:
  def __init__(self, raio):
    self.raio = raio

  def calcular_area(self):
    return math.pi * self.raio ** 2

circulo_teste = Circulo(3)
area_do_circulo = circulo_teste.calcular_area()
print(area_do_circulo)

# 2.
class Livro:
  def __init__(self, titulo, autor):
    self.titulo = titulo
    self.autor = autor

  def detalhes(self):
    return f"Título: {self.titulo}\nAutor: {self.autor}"

livro_01 = Livro("O Último Desejo - The Witcher: Volume 1", "Andrzej Sapkowski")
livro_01_detalhes = livro_01.detalhes()
print(livro_01_detalhes)

# 3.
class Retangulo:
  def __init__(self, base, altura):
    self.base = base
    self.altura = altura

  def calcular_area(self):
    return self.base * self.altura

retangulo_teste = Retangulo(10, 5)
area_do_retangulo = retangulo_teste.calcular_area()
print(area_do_retangulo)

# 4.
class ContaBancaria:
    def __init__(self, saldo, titular):
      self.saldo = float(saldo)
      self.titular = titular

    def depositar(self, quantia):
      self.saldo += quantia

    def sacar(self, quantia):
      self.saldo -= quantia


conta_bancaria_01 = ContaBancaria(100, "Gabriel Alves")

print(conta_bancaria_01.saldo)
conta_bancaria_01.depositar(500)
print(conta_bancaria_01.saldo)
print()
print(conta_bancaria_01.saldo)
conta_bancaria_01.sacar(300)
print(conta_bancaria_01.saldo)

# 5.
class Pessoa:
    def __init__(self, nome, idade):
      self.nome = nome
      self.idade = idade

    def falar(self):
      print(f"{self.nome}: Olá!")

pessoa_01 = Pessoa("Gabriel", 22)
pessoa_01.falar()

# 6.
class Produto:
    def __init__(self, nome, preco, quantidade):
      self.nome = nome
      self.preco = float(preco)
      self.quantidade = quantidade

    def calcular_total(self):
      return self.preco * self.quantidade

produto_01 = Produto("Caneta", 5, 100)
print(f"Valor total do produto: R${produto_01.calcular_total()}")

# 7.
class Carro:
    def __init__(self, marca, modelo, ano):
      self.marca = marca
      self.modelo = modelo
      self.ano = ano

    def detalhes(self):
      return f"Marca: {self.marca}\nModelo: {self.modelo}\nAno: {self.ano}"

carro_01 = Carro("Toyota", "Corolla", 2024)
print(carro_01.detalhes())

# 8.
class Aluno:
    def __init__(self, nome, notas):
      self.nome = nome
      self.notas = notas

    def calcular_media(self):
      return sum(self.notas) / len(self.notas)

aluno_01 = Aluno("João", [7.5, 8, 5, 10])
print(aluno_01.calcular_media())

# 9.
class Triangulo:
    def __init__(self, lado1, lado2, lado3):
      self.lado1 = lado1
      self.lado2 = lado2
      self.lado3 = lado3

    def calcular_perimetro(self):
      return self.lado1 + self.lado2 + self.lado3

triangulo_01 = Triangulo(5, 7, 9)
print(triangulo_01.calcular_perimetro())

# 10.
class Funcionario:
    def __init__(self, nome, salario, cargo):
      self.nome = nome
      self.salario = float(salario)
      self.cargo = cargo

    def aumentar_salario(self, percentual_de_aumento):
      self.salario += self.salario * (percentual_de_aumento / 100)

funcionario_01 = Funcionario("André", 1600, "Auxiliar de produção")
print(f"Salário: {funcionario_01.salario}")

funcionario_01.aumentar_salario(15)
print(f"Salário novo: {funcionario_01.salario}")