# -*- coding: utf-8 -*-
"""lista_de_exercicio_05_gabriel_moises_alves.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1URjc_7bbyxxPVFWWVDoHCXLtUhpAwwdB

# LISTA DE EXERCÍCIO – 05: Gabriel Moises Alves
"""

# 1.
class Fila:
  def __init__(self) -> None:
    self.documentos = []

  def inserir_documentos(self, novos_documentos: list) -> None:
    self.documentos += novos_documentos

  def primeiro(self):
    return self.documentos[0]

  def ultimo(self):
    return self.documentos[-1]

  def quantidade(self):
    return len(self.documentos)

fila_documentos = Fila()
fila_documentos.inserir_documentos(["doc1"])
print(f"Documento inserido: {fila_documentos.documentos}")

docs = ["doc2", "doc3"]
fila_documentos.inserir_documentos(docs)
print(f"Documentos inseridos: {fila_documentos.documentos}")

print(f"Primeiro da fila: {fila_documentos.primeiro()}")
print(f"Último da fila: {fila_documentos.ultimo()}")
print(f"Quantidade de documentos na fila: {fila_documentos.quantidade()} documentos")

# 2.
class FilaBanco:
  def __init__(self) -> None:
    self.clientes = []

  def inserir_clientes(self, novos_clientes: list) -> None:
    self.clientes += novos_clientes

  def primeiro(self):
    return self.clientes[0]

  def ultimo(self):
    return self.clientes[-1]

  def quantidade(self):
    return len(self.clientes)

fila_clientes = FilaBanco()
fila_clientes.inserir_clientes(["cliente1"])
print(f"Cliente inserido na fila: {fila_clientes.clientes}")

clientes = ["cliente2", "cliente3", "cliente4"]
fila_clientes.inserir_clientes(clientes)
print(f"Clientes inseridos na fila: {fila_clientes.clientes}")

print(f"Primeiro da fila: {fila_clientes.primeiro()}")
print(f"Último da fila: {fila_clientes.ultimo()}")
print(f"Quantidade de clientes na fila: {fila_clientes.quantidade()} clientes")

# 3.
class FilaRestaurante:
  def __init__(self) -> None:
    self.pedidos = []

  def inserir_pedidos(self, novos_pedidos: list) -> None:
    self.pedidos += novos_pedidos

  def primeiro(self):
    return self.pedidos[0]

  def ultimo(self):
    return self.pedidos[-1]

  def quantidade(self):
    return len(self.pedidos)

fila_pedidos = FilaRestaurante()
fila_pedidos.inserir_pedidos(["p1", "p2"])
print(f"Clientes na fila: {fila_pedidos.pedidos}")

pedidos_novos = ["p3", "p4", "p5"]
fila_pedidos.inserir_pedidos(pedidos_novos)
print(f"Clientes na fila: {fila_pedidos.pedidos}")

print(f"Primeiro da fila: {fila_pedidos.primeiro()}")
print(f"Último da fila: {fila_pedidos.ultimo()}")
print(f"Quantidade de pedidos na fila: {fila_pedidos.quantidade()} pedidos")

# 4.
class FilaTarefas:
  def __init__(self) -> None:
    self.tarefas = []

  def inserir_tarefas(self, novas_tarefas: list) -> None:
    self.tarefas += novas_tarefas

  def concluir_tarefa(self) -> None:
    self.tarefas.pop(0)

fila_tarefas = FilaTarefas()

fila_tarefas.inserir_tarefas(["tarefa1", "tarefa2", "tarefa3"])
print(f"Tarefas adicionadas: {fila_tarefas.tarefas}")

fila_tarefas.concluir_tarefa()
print(f"Concluir tarefa: {fila_tarefas.tarefas}")

fila_tarefas.concluir_tarefa()
print(f"Concluir tarefa: {fila_tarefas.tarefas}")

# 5.
class FilaOnline:
  def __init__(self) -> None:
    self.pedidos = []

  def inserir_pedidos(self, novos_pedidos: list) -> None:
    self.pedidos += novos_pedidos

  def processar_pedido(self):
    return self.pedidos.pop(0)

pedidos_online = FilaOnline()

pedidos_online.inserir_pedidos(["p1", "p2", "p3"])
print(f"Pedidos adicionados: {pedidos_online.pedidos}")

print("=== Processar pedido ===")
print(f"Pedido processado: {pedidos_online.processar_pedido()}")
print(f"Pedidos na fila: {pedidos_online.pedidos}")

# 6.
class PilhaNavegador:
  def __init__(self) -> None:
    self.historico_paginas = []
    self.pagina_atual = "nova aba"

  def inserir_paginas(self, novas_paginas: list) -> None:
    self.historico_paginas += novas_paginas

  def avancar(self) -> None:
    if self.pagina_atual == "nova aba":
      self.pagina_atual = self.historico_paginas[0]
    else:
      index_pagina_atual = self.historico_paginas.index(self.pagina_atual)

      if index_pagina_atual < len(self.historico_paginas) - 1:
        self.pagina_atual = self.historico_paginas[index_pagina_atual + 1]
      else:
        print(f"Você já está na última página: {self.pagina_atual}")

  def voltar(self) -> None:
    if self.pagina_atual == "nova aba":
      print(f"Não há páginas anteriores. Você está na nova aba: {self.pagina_atual}")
    else:
      index_pagina_atual = self.historico_paginas.index(self.pagina_atual)

      if index_pagina_atual > 0:
        self.pagina_atual = self.historico_paginas[index_pagina_atual - 1]
      else:
        print(f"Você já está na primeira página: {self.pagina_atual}")

navegador = PilhaNavegador()
navegador.inserir_paginas(["site10", "site11", "site12"])

print(f"Histórico de páginas: {navegador.historico_paginas}")
print(f"Página atual: {navegador.pagina_atual}")

print("\nAvançar página")
navegador.avancar()
print(f"Página atual: {navegador.pagina_atual}")

print("\nAvançar página")
navegador.avancar()
print(f"Página atual: {navegador.pagina_atual}")

print("\nAvançar página")
navegador.avancar()
print(f"Página atual: {navegador.pagina_atual}")

print("\nAvançar página")
navegador.avancar()
print(f"Página atual: {navegador.pagina_atual}")

print("\nVoltar página")
navegador.voltar()
print(f"Página atual: {navegador.pagina_atual}")

print("\nVoltar página")
navegador.voltar()
print(f"Página atual: {navegador.pagina_atual}")

print("\nVoltar página")
navegador.voltar()
print(f"Página atual: {navegador.pagina_atual}")

# 7.
class PilhaCalculadoraRPN:
  def __init__(self) -> None:
    self.expressao = []

  def inserir_expressão(self, expressao: list[float, str]):
    self.expressao += expressao

  def calcular(self) -> float:
    operandos = []

    for valor in self.expressao:
      if isinstance(valor, (int, float)):
        operandos.append(valor)
      elif isinstance(valor, str):
        operando2 = operandos.pop()
        operando1 = operandos.pop()

        if valor == "+":
          operandos.append(operando1 + operando2)
        elif valor == "-":
          operandos.append(operando1 - operando2)
        elif valor == "*":
          operandos.append(operando1 * operando2)
        elif valor == "/":
          operandos.append(operando1 / operando2)
        else:
          print(f"O operador '{valor}' é inválido")

    return operandos[0]

calculadora = PilhaCalculadoraRPN()

calculadora.inserir_expressão([3.0, 4.0, "+", 2.0, "*"])

print(calculadora.calcular())

# 8.
class PilhaEditorTexto:
  def __init__(self) -> None:
    self.texto = []
    self.desfeito = str

  def inserir_texto(self, texto: str):
    self.texto += [texto]

  def desfazer(self):
    self.desfeito = self.texto.pop()

  def refazer(self):
    if isinstance(self.desfeito, str):
      self.inserir_texto(self.desfeito)
    else:
      print("Não há alterações para refazer.")

editor_texto = PilhaEditorTexto()

print("Inserir texto")
editor_texto.inserir_texto("Boa noite, ")
editor_texto.inserir_texto("caro inimigo")
print(editor_texto.texto)

print("Desfazer")
editor_texto.desfazer()
print(editor_texto.texto)

print("Refazer")
editor_texto.refazer()
print(editor_texto.texto)

# 9.
class PilhaLeitorOperador:
  def __init__(self) -> None:
    self.expressoes = []

  def inserir_expressao(self, expressao: str) -> None:
    self.expressoes += [expressao]

  def obter_operadores(self) -> list[str]:
    operadores_totais = []

    for expressao in self.expressoes:
      operadores = []

      for char in expressao:
        if char in ("+", "-", "*", "/", "%", "^"):
          operadores.append(char)

      operadores_totais.append(operadores)

    return operadores_totais

  def imprimir_operadores(self) -> None:
    print(f"Operadores: {self.obter_operadores()}")

leitor_operador = PilhaLeitorOperador()
leitor_operador.inserir_expressao("(2+3)*(8-9)/(7^3)")
leitor_operador.inserir_expressao("(5-1)/(1*2)")

leitor_operador.imprimir_operadores()

# 10.
class PilhaLeitorPalindromo:
  def __init__(self) -> None:
    self.palavra = str
    self.palavra_caracteres = []

  def inserir_palavra(self, palavra: str) -> None:
    self.palavra = palavra

  def empilhar_caracteres(self) -> None:
    for char in self.palavra:
      self.palavra_caracteres.append(char)

  def eh_palindromo(self) -> bool:
    self.empilhar_caracteres()
    palavra_caracteres_reverso = list(reversed(self.palavra_caracteres))

    return palavra_caracteres_reverso == self.palavra_caracteres

  def imprimir_eh_palindromo(self) -> None:
    print(f"A palavra '{self.palavra}' {"é" if self.eh_palindromo() else "não é"} um palíndromo.")

leitor_palindromo = PilhaLeitorPalindromo()
leitor_palindromo.inserir_palavra("radar")
leitor_palindromo.imprimir_eh_palindromo()

leitor_palindromo = PilhaLeitorPalindromo()
leitor_palindromo.inserir_palavra("leite")
leitor_palindromo.imprimir_eh_palindromo()

leitor_palindromo = PilhaLeitorPalindromo()
leitor_palindromo.inserir_palavra("osso")
leitor_palindromo.imprimir_eh_palindromo()

leitor_palindromo = PilhaLeitorPalindromo()
leitor_palindromo.inserir_palavra("macaco")
leitor_palindromo.imprimir_eh_palindromo()