# -*- coding: utf-8 -*-
"""lista_de_exercicio_04_gabriel_moises_alves.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSbs5_uzQCwEY0AYEbOUeIg-JgfUsPlS

# LISTA DE EXERCÍCIO – 04: Gabriel Moises Alves
"""

# 1.
def select_sort(vetor):

  n=len(vetor)

  for i in range(n):
    id_min=i
    for j in range(i+1,n):
      if vetor[id_min]>vetor[j]:
        id_min=j

    aux=vetor[i]
    vetor[i]=vetor[id_min]
    vetor[id_min]=aux

  return (vetor)

vetor = [10, 15, 14, 13, 12, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9]

select_sort(vetor)

# 2.
from typing import Literal

def ordenar(lista: list, tipo: Literal["crescente", "decrescente"] = "crescente") -> None:
  if tipo == "crescente":
    lista.sort()
  else:
     lista.sort(reverse=True)

vetor = [10, 15, 14, 13, 12, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9]

ordenar(vetor)
print(vetor)

ordenar(vetor, "decrescente")
print(vetor)

# 3.
def maior_valor(lista: list) -> int:
  maior_valor = lista[0]

  for valor in lista[1:]:
    if valor > maior_valor:
      maior_valor = valor

  return maior_valor

def menor_valor(lista: list) -> int:
  menor_valor = lista[0]

  for valor in lista[1:]:
    if valor < menor_valor:
      menor_valor = valor

  return menor_valor

vetor = [10, 15, 14, 13, 12, 11, 1, 22, 3, 4, 5, 6, 17, 8, 9]

print(f"Maior valor: {maior_valor(vetor)}")
print(f"Menor valor: {menor_valor(vetor)}")

# 4.
def segundo_menor_valor(lista: list) -> int:
  return sorted(lista)[1]

vetor = [10, 15, 14, 13, 12, 11, 1, 2, 3, 4, 2, 6, 7, 8, 9]
print(segundo_menor_valor(vetor))

# 5.
def remover_duplicados(lista: list) -> list:
  lista_formatada = lista

  for valor in lista_formatada:
    contador_valor = 0

    for i in range(len(lista_formatada)):
      if lista_formatada[i] == valor:
        contador_valor += 1

      if contador_valor > 1:
        lista_formatada.pop(i)
        contador_valor -= 1

  return lista_formatada

vetor = [1, 2, 4, 2, 1]
print(remover_duplicados(vetor))

# 6.
def contador_pares_impares(lista: list) -> dict:
  contador = {
      "pares": 0,
      "impares": 0
  }

  for valor in lista:
    if valor % 2 == 0:
      contador["pares"] += 1
    else:
      contador["impares"] += 1

  return contador

vetor = [1, 2, 3, 4, 2, 1, 7]
vetor.sort(reverse=True)

print(vetor)
print(contador_pares_impares(vetor))

# 7.
def terceiro_maior_valor(lista: list) -> int:
  return sorted(lista, reverse=True)[2]

vetor_1 = [-1, 15, 13, 12, 11, 2, 6, 7, 9]
print(terceiro_maior_valor(vetor_1))

vetor_2 = [1, 2, 4, 2, 1]
print(terceiro_maior_valor(vetor_2))

# 8.
def mediana(lista: list) -> int:
  lista_ordenada = sorted(lista)
  return lista_ordenada[round((len(lista) - 1) / 2)]

vetor_1 = [1, 2, 4, 2, 1]
print(mediana(vetor_1))