# -*- coding: utf-8 -*-
"""lista_de_exercicio_01_gabriel_moises_alves.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K3HVx7XoEM-p1XfsCNIGcKBeu46tCblP

# LISTA DE EXERCÍCIO – 01: Gabriel Moises Alves
"""

# 1.
def media(n1, n2, n3):
  return (n1 + n2 + n3) / 3

print("Digite três números inteiros:")
n1 = int(input("1: "))
n2 = int(input("2: "))
n3 = int(input("3: "))

print(f"\n{media(n1, n2, n3)}")

# 2.
def par_ou_impar(numero):
  if numero % 2 == 0:
    print(f"{numero} é par!")
  else:
    print(f"{numero} é ímpar!")

numero_usuario = int(input("Digite um número inteiro: "))
par_ou_impar(numero_usuario)

# 3.
def pares_ate_numero(numero):
  for i in range(0, numero + 1, 2):
    print(i)

numero_usuario = int(input("Digite um número inteiro: "))
pares_ate_numero(numero_usuario)

# 4.
def lista_min_max(lista_de_numeros):
  print(f"Maior valor: {max(lista_de_numeros)}\nMenor valor: {min(lista_de_numeros)}")

lista_min_max([1, 5, 3, 10, 9, -2])

# 5.
def media_pares(lista_de_numeros):
  pares = []

  for n in lista_de_numeros:
    if n % 2 == 0:
      pares.append(n)

  return sum(pares) / len(pares)

print(media_pares([1, 5, 4, 8, 9]))

# 6.
def fatorial(n):
  fatorial = n

  for i in range(n - 1, 0, -1):
    fatorial *= i

  return fatorial

numero_usuario = int(input("Digite um número inteiro positivo: "))
fatorial(numero_usuario)

# 7.
import math

def sequencia_fibonacci(n):
  if n <= 0:
    return []
  elif n == 1:
    return [0]

  sequencia = [0, 1]

  for i in range(2, n + 2):
    sequencia.append(sequencia[-1] + sequencia[-2])
    print(f"{sequencia[-2]} + {sequencia[-3]} = {sequencia[-1]}")

input_usuario = int(input("Sequência de Fibonacci:\nDigite quantas vezes repetir: "))
sequencia_fibonacci(input_usuario)

# 8.
from sympy import isprime

def eh_primo(n):
  if isprime(n):
    print(f"\n{n} é número primo!")
  else:
    print(f"\n{n} não é número primo!")

numero_usuario = int(input("É primo?:\nDigite um número: "))
eh_primo(numero_usuario)

# 9.
def nomes_com_a(nomes):
  nomes_com_a = [];

  for nome in nomes:
    if nome[0].lower() == "a":
      nomes_com_a.append(nome)

  return nomes_com_a

nomes_com_a(["Gabriel", "Lucas", "Amanda", "Mariana", "Beatriz", "Ana", "Rodrigo", "Abreu"])